[package]
name = "dj"
authors = ["Vlad Barmichev <barmichev@gmail.com"]
description = "Console launcher for Django applications."
version = "0.1.6"
edition = "2024"
rust-version = "1.93"
license = "MIT"
documentation = "README.md"
repository = "https://github.com/Shindler7/dj"

[profile.release]
panic = "abort"
opt-level = 3
lto = "thin"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dotenvy = "0.15"
log = { version = "0" }
env_logger = { version = "0" }
regex = "1"
serde = { version = "1", features = ["derive"] }
toml = "1"

[lints.rust]
deprecated = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
nonstandard_style = { level = "warn", priority = -1 }
redundant_lifetimes = "warn"
unreachable_pub = "warn"
unsafe_code = "warn"
unused_crate_dependencies = "warn"
unused_must_use = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
clone_on_ref_ptr = "warn"
unwrap_used = "warn"
expect_used = "warn"
